apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: onlineboutique
components:
- for-virtualservice-host
- authorization-policies/for-namespace
- authorization-policies/for-ingress-gateway
#- sidecars/for-namespace
